--1
SELECT IME, MESTO_ROD, GODINA_ROD
FROM GLUMAC
WHERE BROJ = 50;
--2
SELECT IME
FROM GLUMAC
WHERE GODINA_ROD > 1920;
--3
SELECT DISTINCT GLUMAC
FROM IGRA
WHERE FILM BETWEEN 85 AND 91;
--4
SELECT BROJ, NASLOV
FROM FILM
WHERE AA_NAGRADE IS NOT NULL AND TIP = 'comedy';
--5
SELECT COUNT(*)
FROM IZNAJMLJIVANJE
WHERE CLAN = 3
GROUP BY CLAN;
--6
SELECT BROJ, NASLOV 
FROM FILM
WHERE TIP = 'comedy' AND AA_NAGRADE IS NOT NULL AND NASLOV NOT LIKE '%uncle%' AND GODINA > 1970;

